// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dream

import (
	"dm-server/api/dream"
)

type ControllerV1 struct{}

func NewV1() dream.IDreamV1 {
	return &ControllerV1{}
}
