services:
  # PostgreSQL database service
  postgres:
    image: postgres:18.4
    container_name: dream-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dream_server
      POSTGRES_USER: dream_user
      POSTGRES_PASSWORD: 1a^cMnYk5jqb
    volumes:
      - ./volume/postgresql:/var/lib/postgresql
      # init sql file
      - ./resource/database/0-create-tables.sql:/docker-entrypoint-initdb.d/0-create-tables.sql
    ports:
      - "5432:5432"
