package dream

import (
	"context"
	"dm-server/internal/consts"
	"dm-server/internal/dao"
	"dm-server/internal/model"
	"dm-server/internal/model/entity"
	"dm-server/internal/service"
	"dm-server/internal/utility/limiter"
	"errors"
	"fmt"
	"regexp"
	"strings"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/glog"
	"github.com/gogf/gf/v2/text/gregex"
	"github.com/gogf/gf/v2/text/gstr"
)

// AIServiceSelector Define AI service selector interface
type AIServiceSelector interface {
	AnalyzeDreamStream(ctx context.Context, prompt, content string) (<-chan model.DreamStreamEvent, error)
}

type sDream struct {
	providerCall func(context.Context, string, string, string) (<-chan model.DreamStreamEvent, error)
}

func New() *sDream {
	return &sDream{}
}

func init() {
	service.RegisterDream(New())
}

func (s *sDream) ExtractDreamSymbols(ctx context.Context, content string, emotionTags []string) ([]string, error) {
	return shareKnowledge.extractSymbols(ctx, content, filterEmotionTags(emotionTags...))
}

func (s *sDream) SinkDreamSymbolCache(ctx context.Context, userId string, symbols []string, interpretation string, sourceDreamId string) error {
	return shareKnowledge.sinkSymbolCache(ctx, userId, symbols, interpretation, sourceDreamId)
}

// StreamDream Real-time streaming dream analysis
func (s *sDream) StreamDream(ctx context.Context, content string) (<-chan model.DreamStreamEvent, error) {
	ch := make(chan model.DreamStreamEvent, 10)

	// Try to acquire concurrency quota before starting worker goroutine
	if !limiter.Acquire(ctx) {
		// Immediately return a channel that pushes one error
		go func() {
			defer close(ch)
			ch <- model.DreamStreamEvent{Type: model.DreamStreamEventError, Message: "Service busy, please try again later", FinishReason: "busy"}
		}()
		return ch, nil
	}

	go func() {
		defer close(ch)
		// Ensure quota is released
		defer limiter.Release()

		// Check ctx before any time-consuming operation
		select {
		case <-ctx.Done():
			return
		default:
		}

		// Get user openid from ctx
		userid := ctx.Value(consts.CtxUserId)
		if g.IsEmpty(userid) {
			glog.Async(true).Error(ctx, fmt.Errorf("failed to get user id"))
			ch <- model.DreamStreamEvent{Type: model.DreamStreamEventError, Message: "服务繁忙，请稍候再试", FinishReason: "user_context_error"}
			return
		}

		// Get user openid for rate limiting
		openidValue := ctx.Value(consts.CtxOpenId)
		if g.IsEmpty(openidValue) {
			// If openid is not in ctx, get it from database
			var user *entity.Users
			err := dao.Users.Ctx(ctx).Where("id", userid).Scan(&user)
			if err != nil || user == nil {
				glog.Async(true).Error(ctx, fmt.Errorf("failed to get user info: %v", err))
				ch <- model.DreamStreamEvent{Type: model.DreamStreamEventError, Message: "服务繁忙，请稍候再试", FinishReason: "user_lookup_error"}
				return
			}
			openidValue = user.Openid
		}

		// Check user analysis count limit
		if !limiter.CheckUserAnalysisLimit(ctx, openidValue.(string)) {
			glog.Async(true).Infof(ctx, "User %s exceeds analysis count limit", openidValue)
			ch <- model.DreamStreamEvent{Type: model.DreamStreamEventError, Message: "您已达到小时内分析次数上限，请稍后再试", FinishReason: "rate_limit"}
			return
		}

		userIdStr := fmt.Sprintf("%v", userid)
		emotionTags := dreamEmotionTagsFromContext(ctx)

		// Fetch knowledge passages and extracted symbols. L1 symbol cache is metadata only;
		// final dream analysis must always be generated by the LLM.
		interpretResp, err := shareKnowledge.interpretDream(ctx, content, userIdStr, emotionTags)
		if err != nil {
			glog.Warningf(ctx, "知识库L1解析失败: %v", err)
		}
		if interpretResp != nil {
			setDreamStreamMetadata(ctx, interpretResp)
		}

		kw := interpretResp.toSearchResponse()
		if kw == nil {
			// Fall back to the legacy search endpoint for older knowledge-service deployments.
			kw, err = shareKnowledge.search(ctx, content)
			if err != nil {
				// If knowledge base search fails, it should not cause the entire analysis process to fail, just log it
				glog.Warningf(ctx, "知识库搜索失败: %v", err)
			}
		}

		// 3. Format knowledge base content
		var knowledgeContent string
		if shareKnowledge != nil {
			knowledgeContent = shareKnowledge.formatKnowledge(kw)
		}
		glog.Infof(ctx, "知识库内容: %s", knowledgeContent)

		// 4. Get dream analysis prompt
		prompt, err := g.Cfg().Get(ctx, "prompts.dream_analysis")
		if err != nil {
			ch <- model.DreamStreamEvent{Type: model.DreamStreamEventError, Message: "Get dream analysis prompt failed", FinishReason: "config_error"}
			return
		}
		responseLocale := resolveDreamResponseLocale(ctx, content)
		inputLocale := detectDreamInputLocale(content)
		fullPrompt := fmt.Sprintf("```\n# Dream Analysis Expert System Instructions\n\n%s\n", buildDreamLanguageContract(responseLocale, inputLocale))

		// 5. If there is relevant knowledge, append it to the prompt
		if knowledgeContent != "" {
			fullPrompt = fmt.Sprintf("%s## Retrieved Knowledge Instructions\nThe following passages were retrieved from the knowledge base after analyzing the user's dream. They may be written in Chinese and may be partially mismatched. Use them only as reference material, translate or paraphrase them as needed, and keep the final answer in the target output language.\n\n%s", fullPrompt, knowledgeContent)
		}
		if relatedContent := formatRelatedDreamContext(ctx); relatedContent != "" {
			fullPrompt = fmt.Sprintf("%s## Related Dream History\nThe following items are the most relevant past dreams recorded by the same user. Treat them as personalization context and prioritize recurring emotions, scenes, and images over generic symbol explanations. Keep the final answer in the target output language.\n\n%s", fullPrompt, relatedContent)
		}

		fullPrompt += prompt.String()

		// 6. Call AI service to analyze dream (select service according to configuration)
		contentChan, err := s.analyzeDreamStream(ctx, fullPrompt, content)
		if err != nil {
			// Do not use Error to write logs when the request is canceled
			if errors.Is(err, context.Canceled) {
				glog.Async(true).Info(ctx, "stream canceled by client")
				return
			}
			glog.Async(true).Error(ctx, err)
			ch <- model.DreamStreamEvent{Type: model.DreamStreamEventError, Message: "Call AI service to analyze dream failed", FinishReason: "provider_error"}
			return
		}
		glog.Async(true).Infof(ctx, "AI_Service analysis started successfully")

		for {
			select {
			case <-ctx.Done():
				// Cancel: Stop consuming LLM output and exit
				glog.Async(true).Info(ctx, "stream canceled by client")
				return
			case event, ok := <-contentChan:
				if !ok {
					ch <- model.DreamStreamEvent{Type: model.DreamStreamEventError, Message: "AI stream closed without terminal event", FinishReason: "protocol_error"}
					return
				}
				if event.Type == model.DreamStreamEventDelta && event.Content == "" {
					continue
				}
				ch <- event
				if event.Terminal() {
					return
				}
			}
		}
	}()

	return ch, nil
}

func resolveDreamResponseLocale(ctx context.Context, content string) string {
	if locale, ok := ctx.Value(consts.CtxDreamResponseLocale).(string); ok {
		if normalized := normalizeDreamLocale(locale); normalized != "" {
			return normalized
		}
	}
	if detected := detectDreamInputLocale(content); detected != "" {
		return detected
	}
	return "en"
}

func normalizeDreamLocale(locale string) string {
	locale = strings.ToLower(strings.TrimSpace(strings.ReplaceAll(locale, "_", "-")))
	switch {
	case locale == "en" || strings.HasPrefix(locale, "en-"):
		return "en"
	case locale == "zh" || locale == "zh-hans" || locale == "zh-cn" || locale == "zh-sg" || locale == "zh-my":
		return "zh-Hans"
	case locale == "zh-hant" || locale == "zh-tw" || locale == "zh-hk" || locale == "zh-mo":
		return "zh-Hant"
	default:
		return ""
	}
}

func detectDreamInputLocale(content string) string {
	var latinCount, hanCount, hantHintCount int
	for _, r := range content {
		switch {
		case r >= 'A' && r <= 'Z' || r >= 'a' && r <= 'z':
			latinCount++
		case r >= '\u4e00' && r <= '\u9fff':
			hanCount++
			if strings.ContainsRune("夢門風雲龍馬鳥魚愛聽說話見萬與為來這裡後靈體關開時會", r) {
				hantHintCount++
			}
		}
	}
	if hanCount > latinCount {
		if hantHintCount > 0 {
			return "zh-Hant"
		}
		return "zh-Hans"
	}
	if latinCount > 0 {
		return "en"
	}
	return "en"
}

func dreamLocaleName(locale string) string {
	switch locale {
	case "zh-Hans":
		return "Simplified Chinese"
	case "zh-Hant":
		return "Traditional Chinese"
	default:
		return "English"
	}
}

func buildDreamLanguageContract(responseLocale, inputLocale string) string {
	return fmt.Sprintf(`## Output Language Contract (Highest Priority)
Target output locale: %s (%s)
Detected dream input locale: %s (%s)

The app supports exactly three output languages: English (en), Simplified Chinese (zh-Hans), and Traditional Chinese (zh-Hant).
You must write the entire final answer in the target output language, including the title, section headings, table headers, bullets, warnings, and advice.
Retrieved knowledge and related-dream context may be in Chinese; they are reference material only and must not decide the output language.
If the target output locale is en, do not use Chinese fixed templates such as "梦境元素映射", "多元解析视角", or "现实结合".
If the target output locale is zh-Hans, use Simplified Chinese characters.
If the target output locale is zh-Hant, use Traditional Chinese characters.
For the title: use exactly 4 Chinese characters for zh-Hans or zh-Hant; use a natural 2-6 word English title for en.
`, responseLocale, dreamLocaleName(responseLocale), inputLocale, dreamLocaleName(inputLocale))
}

func setDreamStreamMetadata(ctx context.Context, resp *interpretDreamResponse) {
	if resp == nil {
		return
	}
	metadata, ok := ctx.Value(consts.CtxDreamStreamMetadata).(*consts.DreamStreamMetadata)
	if !ok || metadata == nil {
		return
	}
	if symbols := normalizeSymbols(resp.Data.SymbolsDetected); len(symbols) > 0 {
		metadata.SymbolsDetected = symbols
	}
	if symbols := normalizeSymbols(resp.Data.SymbolsMatched); len(symbols) > 0 {
		metadata.SymbolsMatched = symbols
	}
	metadata.InferenceLevel = strings.TrimSpace(resp.Data.InferenceLevel)
}

func dreamEmotionTagsFromContext(ctx context.Context) []string {
	value := ctx.Value(consts.CtxDreamEmotionTags)
	switch tags := value.(type) {
	case []string:
		return filterEmotionTags(tags...)
	case string:
		return filterEmotionTags(tags)
	default:
		return nil
	}
}

func filterEmotionTags(tags ...string) []string {
	filtered := make([]string, 0, len(tags))
	for _, tag := range tags {
		tag = strings.TrimSpace(tag)
		if tag == "" {
			continue
		}
		filtered = append(filtered, tag)
	}
	if len(filtered) == 0 {
		return nil
	}
	return filtered
}

func formatRelatedDreamContext(ctx context.Context) string {
	items, _ := ctx.Value(consts.CtxDreamRelatedContext).([]consts.DreamRelatedContextItem)
	if len(items) == 0 {
		return ""
	}

	var builder strings.Builder
	for _, item := range items {
		summary := strings.TrimSpace(item.Summary)
		if summary == "" {
			summary = "历史梦境摘要暂缺"
		}
		symbols := strings.Join(item.Symbols, "、")
		if symbols == "" {
			symbols = item.Emotion
		}
		builder.WriteString(fmt.Sprintf(
			"- %s: %s (images: %s; emotion: %s; similarity: %.0f%%)\n",
			item.Date,
			summary,
			symbols,
			item.Emotion,
			item.Similarity*100,
		))
	}
	builder.WriteString("\nAt the end of the analysis, add 1-2 natural sentences about recurring cross-dream patterns in the target output language.")
	return builder.String()
}

// Clean text and extract title from text
func cleanText(text string) (string, string) {
	// Remove <think>.+</think> tags and the text inside them
	re1 := regexp.MustCompile(`(?s)\n?\s*<think>.*?</think>\s*\n?`)
	clearText := re1.ReplaceAllString(text, "")

	// Remove leading newlines
	clearText = gstr.Replace(clearText, "\n+", "")

	// Get the next line as title
	titleText := gstr.Split(clearText, "\n")[0]
	// Ensure it starts with '#' character
	if strings.HasPrefix(gstr.Trim(titleText), "#") {
		// Get text between 「」 as title
		match, err := gregex.MatchString(`「(.+?)」`, titleText)
		if err != nil {
			return "", clearText
		}
		if len(match) < 2 {
			return "", clearText
		}
		titleText = match[1]
	}
	return gstr.Trim(titleText), gstr.Trim(clearText)
}
