// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package history

import (
	"dm-server/api/history"
)

type ControllerV1 struct{}

func NewV1() history.IHistoryV1 {
	return &ControllerV1{}
}
