// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dm-server/internal/dao/internal"
)

// analysisSessionsDao is the data access object for the table analysis_sessions.
// You can define custom methods on it to extend its functionality as needed.
type analysisSessionsDao struct {
	*internal.AnalysisSessionsDao
}

var (
	// AnalysisSessions is a globally accessible object for table analysis_sessions operations.
	AnalysisSessions = analysisSessionsDao{internal.NewAnalysisSessionsDao()}
)

// Add your custom methods and functionality below.
