// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dm-server/internal/dao/internal"
)

// dreamsDao is the data access object for the table dreams.
// You can define custom methods on it to extend its functionality as needed.
type dreamsDao struct {
	*internal.DreamsDao
}

var (
	// Dreams is a globally accessible object for table dreams operations.
	Dreams = dreamsDao{internal.NewDreamsDao()}
)

// Add your custom methods and functionality below.
