// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dm-server/internal/dao/internal"
)

// systemConfigsDao is the data access object for the table system_configs.
// You can define custom methods on it to extend its functionality as needed.
type systemConfigsDao struct {
	*internal.SystemConfigsDao
}

var (
	// SystemConfigs is a globally accessible object for table system_configs operations.
	SystemConfigs = systemConfigsDao{internal.NewSystemConfigsDao()}
)

// Add your custom methods and functionality below.
